[project]
authors = ["Nizar Septian <nizar47@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Moments2Amplitudes"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
